CREATE TABLE IF NOT EXISTS food_logs (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    meal_type VARCHAR(50) NOT NULL,
    food_name VARCHAR(255) NOT NULL,
    calories INT NOT NULL,
    logged_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
