spring:
  application:
    name: analytics-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:analytics;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
fitverse:
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  minio:
    endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
    access-key: ${MINIO_ACCESS_KEY:minio}
    secret-key: ${MINIO_SECRET_KEY:minio123}
    bucket: ${MINIO_BUCKET:fitverse}
  security:
    jwt:
      secret: ${JWT_SECRET:ZmFsbGJhY2stZGVmYXVsdC1zZWNyZXQ=}
      issuer: fitverse-platform
      access-token-validity-seconds: ${JWT_ACCESS_TOKEN_SECONDS:7200}
  ai:
    chat:
      provider: ${FITVERSE_CHAT_PROVIDER:echo}
      model: ${FITVERSE_CHAT_MODEL:gpt-4o}
    food:
      model-path: ${FOOD_MODEL_PATH:models/foodvision.pb}
